In [1]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [9]:
ej_1=np.random.randint(10,100,50)
print(ej_1)
print('------------')
#No estamos seguras de si se refiere a empezar en el índice 5 o la quinta posición empezando desde el 0
print(ej_1[4::5])
print('------------')
print(ej_1[5::5])

[81 16 27 50 29 46 51 63 62 87 99 29 13 79 83 98 27 33 77 26 54 28 54 33
 36 32 59 47 74 88 92 98 85 86 49 76 71 74 70 43 73 27 48 14 97 23 83 68
 41 17]
------------
[29 87 83 26 36 88 49 43 97 17]
------------
[46 99 98 54 32 92 76 73 23]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares

In [10]:
ej_2=np.random.randint(1,21,30)
print(ej_2)
print('------------')
#No estamos seguras de si se refiere a empezar en el índice 1 o los impares empezando desde el 0
print(ej_2[::2])
print('------------')
print(ej_2[1::2])

[ 3 20 18 20  4 20 15  9  3  5  2  4  1  1  7 11  6 13 17  5 19  9  8  4
 15  4 15  2  2  2]
------------
[ 3 18  4 15  3  2  1  7  6 17 19  8 15 15  2]
------------
[20 20 20  9  5  4  1 11 13  5  9  4  4  2  2]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [20]:
ej_3=np.random.rand(4,6)*3
print(ej_3)
print('------------')
print(np.round(ej_3[-1:],2))


[[1.308898   1.17220747 2.48792079 1.16097359 0.79611882 1.51572498]
 [0.31966978 0.75788587 0.01947728 2.34192529 0.80619376 1.62449173]
 [1.7048666  2.48387286 2.84458421 2.59895493 1.36860986 2.5799569 ]
 [0.94951327 0.42522066 1.56370766 0.71641285 2.11336554 0.22012662]]
------------
[[0.95 0.43 1.56 0.72 2.11 0.22]]
------------
[20 20 20  9  5  4  1 11 13  5  9  4  4  2  2]


4.Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [34]:
ej_4=np.random.rand(6,4)
print(ej_4)
print('------------')
print(np.round(ej_4[:,1],2))
#print(ej_4[:,1])

[[0.65854632 0.15806306 0.62132609 0.24777853]
 [0.01442123 0.61658514 0.34851441 0.56097065]
 [0.60881468 0.56358725 0.47955142 0.50335716]
 [0.77961804 0.92351459 0.21968248 0.88800475]
 [0.14072396 0.0374803  0.61824672 0.58552968]
 [0.44253621 0.84384397 0.60554222 0.26361758]]
------------
[0.16 0.62 0.56 0.92 0.04 0.84]


5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [37]:
ej_5=np.random.randint(-50,51,30)
print(ej_5)
print('------------')

print(ej_5[ej_5<0])


[ 18 -13  21  33  22 -32 -10  41 -31  -3  37   7 -24  23 -24  30 -30 -29
  -7  -2   7   0   8  45  42 -24  12 -27  35 -14]
------------
[-13 -32 -10 -31  -3 -24 -24 -30 -29  -7  -2 -24 -27 -14]


6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [46]:
ej_6=np.random.rand(10)
print(np.round(ej_6,2))
print('------------')
print(np.where(ej_6>0.5))

[0.32 0.86 0.31 0.38 0.83 0.09 0.93 0.48 0.71 0.46]
------------
(array([1, 4, 6, 8]),)


7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [50]:
ej_7=np.random.randint(1,101,40)
print(ej_7)
print('------------')
#No estamos seguras de si se refiere a empezar en el índice 5 o la quinta posición empezando desde el 0
div_3=ej_7%3
div_4=ej_7%4
print(ej_7[(div_3==0) & (div_4==0)])


[47 17 86  4  9 10 99 32 16 58 95 23 67 23 82 35 74 25 31 68 17 23 16 92
  7 74  3 48 40 91 64 90 61 18 68 16  1 65 70 90]
------------
[48]


BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

## Reshape y Transpose:

- Ejercicios con reshape

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [52]:
ej_1=np.random.randint(1,101,(2,3,4))
print(ej_1)
print('-------------')
print(np.reshape(ej_1,(4,6)))

[[[35 20 97 32]
  [27  1 87 35]
  [38  4  5 13]]

 [[61  9 56 14]
  [59 40  2 47]
  [19  9 61 21]]]
-------------
[[35 20 97 32 27  1]
 [87 35 38  4  5 13]
 [61  9 56 14 59 40]
 [ 2 47 19  9 61 21]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [54]:
ej_2=np.random.randint(1,60,(3,4,5))
print(ej_2)
print('-------------')
print(np.reshape(ej_2,(5,12)))

[[[ 9 41 44 31 58]
  [ 8 42 34 57 44]
  [28  6 40  8 55]
  [ 1 14 22 31 32]]

 [[41 29 11 18 24]
  [14  4 37 18 49]
  [ 3  5 25  2 27]
  [44 45 53 52 11]]

 [[30  1 49 15 59]
  [30 24  4 47 47]
  [17 19 21 47 51]
  [ 9 45 28 38 49]]]
-------------
[[ 9 41 44 31 58  8 42 34 57 44 28  6]
 [40  8 55  1 14 22 31 32 41 29 11 18]
 [24 14  4 37 18 49  3  5 25  2 27 44]
 [45 53 52 11 30  1 49 15 59 30 24  4]
 [47 47 17 19 21 47 51  9 45 28 38 49]]


3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [56]:
ej_3=np.random.rand(4,3,2)
print(ej_3)
print('-------------')
print(np.reshape(ej_3,(2,12)))

[[[0.7300687  0.43686381]
  [0.45353704 0.18741598]
  [0.24991165 0.61458319]]

 [[0.40493075 0.90001818]
  [0.90510401 0.42811643]
  [0.50930435 0.23707426]]

 [[0.426319   0.35419289]
  [0.02808988 0.90052601]
  [0.5974216  0.9624655 ]]

 [[0.54147698 0.53757553]
  [0.16806058 0.79487201]
  [0.33753669 0.0060372 ]]]
-------------
[[0.7300687  0.43686381 0.45353704 0.18741598 0.24991165 0.61458319
  0.40493075 0.90001818 0.90510401 0.42811643 0.50930435 0.23707426]
 [0.426319   0.35419289 0.02808988 0.90052601 0.5974216  0.9624655
  0.54147698 0.53757553 0.16806058 0.79487201 0.33753669 0.0060372 ]]


- Ejercicios con transpose

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [59]:
print(ej_2)
print('-------------')
print(np.transpose(ej_2,(2,1,0)))

[[[ 9 41 44 31 58]
  [ 8 42 34 57 44]
  [28  6 40  8 55]
  [ 1 14 22 31 32]]

 [[41 29 11 18 24]
  [14  4 37 18 49]
  [ 3  5 25  2 27]
  [44 45 53 52 11]]

 [[30  1 49 15 59]
  [30 24  4 47 47]
  [17 19 21 47 51]
  [ 9 45 28 38 49]]]
-------------
[[[ 9 41 30]
  [ 8 14 30]
  [28  3 17]
  [ 1 44  9]]

 [[41 29  1]
  [42  4 24]
  [ 6  5 19]
  [14 45 45]]

 [[44 11 49]
  [34 37  4]
  [40 25 21]
  [22 53 28]]

 [[31 18 15]
  [57 18 47]
  [ 8  2 47]
  [31 52 38]]

 [[58 24 59]
  [44 49 47]
  [55 27 51]
  [32 11 49]]]


5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [61]:
print(ej_3)
print('-------------')
print(np.transpose(ej_3,(1,2,0)))

[[[0.7300687  0.43686381]
  [0.45353704 0.18741598]
  [0.24991165 0.61458319]]

 [[0.40493075 0.90001818]
  [0.90510401 0.42811643]
  [0.50930435 0.23707426]]

 [[0.426319   0.35419289]
  [0.02808988 0.90052601]
  [0.5974216  0.9624655 ]]

 [[0.54147698 0.53757553]
  [0.16806058 0.79487201]
  [0.33753669 0.0060372 ]]]
-------------
[[[0.7300687  0.40493075 0.426319   0.54147698]
  [0.43686381 0.90001818 0.35419289 0.53757553]]

 [[0.45353704 0.90510401 0.02808988 0.16806058]
  [0.18741598 0.42811643 0.90052601 0.79487201]]

 [[0.24991165 0.50930435 0.5974216  0.33753669]
  [0.61458319 0.23707426 0.9624655  0.0060372 ]]]


## Preguntas teóricas:

6. ¿Qué diferencia existe entre el reshape y el transpose?

El reshape, cambia la forma del array indicando la forma que quieres, mientras que el transpose la cambia utilizando las dimensiones previas cambiando el orden

7. ¿Y entre el transpose y el swapaxes?

El swapaxes sólo cambia 2 dimensiones entre ellas, los ejes.

## Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [62]:
ej_1=np.round(np.random.rand(2,3,5),1)
print(ej_1)

[[[0.6 0.2 0.2 1.  0.4]
  [0.1 0.  0.5 0.4 0.5]
  [0.7 0.9 0.8 0.1 0.1]]

 [[0.3 0.6 0.6 0.6 0.1]
  [0.5 0.8 0.7 0.6 0.8]
  [0.8 0.9 0.7 0.  0.8]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [65]:
ej_2=np.empty((2,3,5))
print(ej_2)
print('-----------')
print(ej_1)

[[[0.6 0.2 0.2 1.  0.4]
  [0.1 0.  0.5 0.4 0.5]
  [0.7 0.9 0.8 0.1 0.1]]

 [[0.3 0.6 0.6 0.6 0.1]
  [0.5 0.8 0.7 0.6 0.8]
  [0.8 0.9 0.7 0.  0.8]]]
-----------
[[[0.6 0.2 0.2 1.  0.4]
  [0.1 0.  0.5 0.4 0.5]
  [0.7 0.9 0.8 0.1 0.1]]

 [[0.3 0.6 0.6 0.6 0.1]
  [0.5 0.8 0.7 0.6 0.8]
  [0.8 0.9 0.7 0.  0.8]]]


- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [69]:
np.round(np.mean(ej_1),1)

0.5

In [76]:
#Si el valor del array es igual que la media, se reemplaza por "A".
ej_2=np.where(ej_2==(np.round(np.mean(ej_1),1)),'A',ej_2)
print(ej_2)

[[['0.6' '0.2' '0.2' '1.0' '0.4']
  ['0.1' '0.0' 'A' '0.4' 'A']
  ['0.7' '0.9' '0.8' '0.1' '0.1']]

 [['0.3' '0.6' '0.6' '0.6' '0.1']
  ['A' '0.8' '0.7' '0.6' '0.8']
  ['0.8' '0.9' '0.7' '0.0' '0.8']]]


/tmp/ipykernel_19942/1642116368.py:2: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  ej_2=np.where(ej_2==(np.round(np.mean(ej_1),1)),'A',ej_2)


In [81]:
#- Si el valor del array es mayor que la media, se reemplaza por "B".
media=np.round(np.mean(ej_1),1)
ej_2=np.where(ej_2>media,'B',ej_2)
print(ej_2)

UFuncTypeError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtype[str_]'>, <class 'numpy.dtype[float64]'>) -> <class 'numpy.dtype[bool_]'>